package UserInterface;

import Business.EmployeeDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Name
 */
public class HospitalAdministrator extends javax.swing.JPanel {

    JPanel container;
    EmployeeDirectory employeeDirectory;
    
    /**
     * Creates new form HospitalAdministrator
     */
    public HospitalAdministrator() {
        
    }

    HospitalAdministrator(JPanel container, EmployeeDirectory employeeDirectory) {
    initComponents();
    this.container = container;
    this.employeeDirectory = employeeDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerDoctor = new javax.swing.JButton();
        registerPatient = new javax.swing.JButton();
        viewPatients = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("             Hospital Administrator");

        registerDoctor.setText("Register Doctor");
        registerDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDoctorActionPerformed(evt);
            }
        });

        registerPatient.setText("Register Patient");
        registerPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPatientActionPerformed(evt);
            }
        });

        viewPatients.setText("View Patients");
        viewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(170, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(registerPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPatients)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDoctorActionPerformed
        DoctorRegistrationForm doctorRegistration = new DoctorRegistrationForm(container);
        container.add("DoctorRegistrationForm", doctorRegistration);
        CardLayout cardLayout = (CardLayout) container.getLayout();
        cardLayout.next(container);
    }//GEN-LAST:event_registerDoctorActionPerformed

    private void registerPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPatientActionPerformed
        System.out.println("UserInterface.HospitalAdministrator.registerPatientActionPerformed()");
        PatientRegistrationForm registerPatientForm = new PatientRegistrationForm(container);
        container.add("PatientRegistrationForm", registerPatientForm);
        CardLayout cardLayout = (CardLayout) container.getLayout();
        cardLayout.next(container);
    }//GEN-LAST:event_registerPatientActionPerformed

    private void viewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientsActionPerformed
        HospitalPatientList hospitalPatientList = new HospitalPatientList(container);
        container.add("HospitalPatientList", hospitalPatientList);
        CardLayout cardLayout = (CardLayout) container.getLayout();
        cardLayout.next(container);
    }//GEN-LAST:event_viewPatientsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerDoctor;
    private javax.swing.JButton registerPatient;
    private javax.swing.JButton viewPatients;
    // End of variables declaration//GEN-END:variables
}
