/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DoctorEmployee;
import Business.EmployeeDirectory;
import Business.SpecialityFactory;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Name
 */
public class RegisterDoctor extends javax.swing.JPanel {

    /**
     * Creates new form RegisterDoctor
     */
//    public RegisterDoctor() {
//        initComponents();
//    }
    private JPanel container;
    EmployeeDirectory employeeDirectory;

    public RegisterDoctor(JPanel container, EmployeeDirectory employeeDirectory) {
        initComponents();
        this.container = container;
        this.employeeDirectory = employeeDirectory;
        populateDoctorComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorFName = new javax.swing.JTextField();
        registerDoctorButton = new javax.swing.JButton();
        doctorLName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doctorsDepartment = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        doctorPhone = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        resetRegistration = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doctorEmail = new javax.swing.JTextField();
        doctorsPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 153, 153));

        doctorFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFNameActionPerformed(evt);
            }
        });

        registerDoctorButton.setText("Register");
        registerDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDoctorButtonActionPerformed(evt);
            }
        });

        doctorLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorLNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Last Name:");

        jLabel7.setText("Department:");

        doctorsDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsDepartmentActionPerformed(evt);
            }
        });

        jLabel5.setText("Phone No:");

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        resetRegistration.setText("Reset");
        resetRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetRegistrationActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Doctor Registration Form");

        jLabel1.setText("First Name:");

        jLabel2.setText("Email:");

        jLabel3.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backjButton)
                        .addGap(27, 27, 27)
                        .addComponent(registerDoctorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetRegistration)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doctorsPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doctorFName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctorLName)
                            .addComponent(doctorsDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(enterpriseLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(doctorFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(doctorsDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(doctorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorsPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerDoctorButton)
                    .addComponent(resetRegistration)
                    .addComponent(backjButton))
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorFNameActionPerformed

    private void registerDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDoctorButtonActionPerformed

        Set<String> emailSet = new HashSet<>();
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader("src/assests/doctorRecord.csv"));
            String line;
            while ((line = br.readLine()) != null) {
                System.out.println(line);
                // use comma as separator
                String[] cols = line.split(",");
                emailSet.add(cols[2]);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PatientRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        String doctorFName = this.doctorFName.getText();
        String doctorLName = this.doctorLName.getText();
        String doctorEmail = this.doctorEmail.getText();
        if (emailSet.contains(doctorEmail)) {
            JOptionPane.showMessageDialog(null, "Doctor with " + doctorEmail + " already exist");
            return;
        }
        String doctorPassword = this.doctorsPassword.getText();
        String doctorPhone = this.doctorPhone.getText();
        String doctorDept = (String) this.doctorsDepartment.getSelectedItem();

        if (doctorFName.equals("") || doctorLName.equals("") || doctorEmail.equals("") || doctorPassword.equals("") || doctorPhone.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
            return;
        }
        /*Start of factory code*/
        SpecialityFactory specialityFactory = new SpecialityFactory();
        DoctorEmployee doctorEmployee = specialityFactory.getObject(doctorDept);
        doctorEmployee.setFirstName(doctorFName);
        doctorEmployee.setLastName(doctorLName);
        doctorEmployee.getUserAccount().setUserName(doctorEmail);
        doctorEmployee.getUserAccount().setUserPassword(doctorPassword);
        doctorEmployee.setPhoneNumber(doctorPhone);
        employeeDirectory.AddEmployeeToDirectory(doctorEmployee);
        /*End of factory code*/
        FileOutputStream fos;
        try {
            fos = new FileOutputStream("src/assests/doctorRecord.csv", true);
            PrintWriter pw = new PrintWriter(fos);
            pw.append(doctorFName + "," + doctorLName + "," + doctorEmail + "," + doctorPassword + "," + doctorPhone + "," + doctorDept);
            pw.println();
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Doctor registered successfully.");
        clearRegistrationDetails();
    }//GEN-LAST:event_registerDoctorButtonActionPerformed

    private void doctorLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorLNameActionPerformed

    private void doctorsDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorsDepartmentActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void resetRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetRegistrationActionPerformed
        // TODO add your handling code here:
        clearRegistrationDetails();
    }//GEN-LAST:event_resetRegistrationActionPerformed
    private void populateDoctorComboBox() {
        // adding doctors department
        doctorsDepartment.addItem(DoctorEmployee.MedicalDepartment.Cardiologist.getValue());
        doctorsDepartment.addItem(DoctorEmployee.MedicalDepartment.Neurologist.getValue());
        doctorsDepartment.addItem(DoctorEmployee.MedicalDepartment.Orthologist.getValue());
        doctorsDepartment.addItem(DoctorEmployee.MedicalDepartment.Pediatrician.getValue());
    }

    private void clearRegistrationDetails() {
        doctorFName.setText("");
        doctorLName.setText("");
        doctorEmail.setText("");
        populateDoctorComboBox();
        doctorsPassword.setText("");
        doctorPhone.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField doctorEmail;
    private javax.swing.JTextField doctorFName;
    private javax.swing.JTextField doctorLName;
    private javax.swing.JTextField doctorPhone;
    private javax.swing.JComboBox<String> doctorsDepartment;
    private javax.swing.JPasswordField doctorsPassword;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton registerDoctorButton;
    private javax.swing.JButton resetRegistration;
    // End of variables declaration//GEN-END:variables
}
